const actionTypes = Object.freeze({
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  //user
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_EMPLOYEE_SUCCESS: "FETCH_EMPLOYEE_SUCCESS",
  FETCH_EMPLOYEE_FAIL: "FETCH_EMPLOYEE_FAIL",

  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAIL: "FETCH_ROLE_FAIL",

  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAIL: "REGISTER_FAIL",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAIL: "EDIT_USER_FAIL",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAIL: "DELETE_USER_FAIL",

  //product

  FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
  FETCH_CATEGORY_FAIL: "FETCH_CATEGORY_FAIL",

  FETCH_PAYMENT_SUCCESS: "FETCH_PAYMENT_SUCCESS",
  FETCH_PAYMENT_FAIL: "FETCH_PAYMENT_FAIL",

  FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAIL: "FETCH_PRODUCT_FAIL",

  FETCH_ALL_PRODUCT_SUCCESS: "FETCH_ALL_PRODUCT_SUCCESS",
  FETCH_ALL_PRODUCT_FAIL: "FETCH_ALL_PRODUCT_FAIL",

  FETCH_PRODUCT_CATEGORY_SUCCESS: "FETCH_PRODUCT_CATEGORY_SUCCESS",
  FETCH_PRODUCT_CATEGORY_FAIL: "FETCH_PRODUCT_CATEGORY_FAIL",

  //order
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAIL: "CREATE_ORDER_FAIL",

  FETCH_ONE_ORDER_SUCCESS: "FETCH_ONE_ORDER_SUCCESS",
  FETCH_ONE_ORDER_FAIL: "FETCH_ONE_ORDER_FAIL",

  FETCH_ALL_ORDER_SUCCESS: "FETCH_ALL_ORDER_SUCCESS",
  FETCH_ALL_ORDER_FAIL: "FETCH_ALL_ORDER_FAIL",

  ADD_PRODUCT_TO_ORDER_SUCCESS: "ADD_PRODUCT_TO_ORDER_SUCCESS",
  ADD_PRODUCT_TO_ORDER_FAIL: "ADD_PRODUCT_TO_ORDER_FAIL",

  //employee
  FETCH_EMPLOYEE_DISCOUNT_SUCCESS: "FETCH_EMPLOYEE_DISCOUNT_SUCCESS",
  FETCH_EMPLOYEE_DISCOUNT_FAIL: "FETCH_EMPLOYEE_DISCOUNT_FAIL",

  // revenue
  FETCH_REVENUE_SUCCESS: "FETCH_REVENUE_SUCCESS",
  FETCH_REVENUE_FAIL: "FETCH_REVENUE_FAIL",
});
export default actionTypes;